{{- with .Values.pantryTrackerBackend -}}
{{- $_ := set .annotations "checksum/configmap" (include (print $.Template.BasePath "/backend/configmap.yaml") $ | sha256sum) -}}
{{- $_ := set .annotations "checksum/secret" (include (print $.Template.BasePath "/backend/secret.yaml") $ | sha256sum) -}}
{{- include "pantry-tracker.backendDeployment" (list $ .) }}
{{- end -}}
