---
registry_secret:
  name: registrypullsecret
  data: ""

pantryTrackerBackend:
  name: backend
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  image:
    repository: ghcr.io/alexdenisova/pantry-tracker-backend
    pullPolicy: Always
    tag: ""
  livenessPath: &livenessPath /health
  readinessPath: *livenessPath
  command:
    - pantry-tracker
    - run
  port: 8080
  configMapValues:
    APP__SOCKET: 0.0.0.0:8080
    APP__DEBUG: "true"
  secretValues:
    APP__DATABASE_URL: ""
    APP__REDIS_URL: ""

backendIngress:
  enabled: true
  host: &host "62.84.119.96.traefik.me"
  className: &ingress_class "ingress-nginx"
  tls:
    secretName: backend-tls
    key: ""
    certificate: ""
  backendRootPath: /api

pantryTrackerFrontend:
  name: frontend
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m
  image:
    repository: ghcr.io/alexdenisova/pantry-tracker-frontend
    pullPolicy: Always
    tag: ""
  port: 5137

frontendIngress:
  enabled: true
  host: *host
  className: *ingress_class
  tls:
    secretName: frontend-tls
    key: ""
    certificate: ""

postgresMigrations:
  name: postgres-migrations
  command:
    - pantry-tracker
    - migrate
