---
registry_secret:
  name: registrypullsecret
  data: ""

pantryTrackerBackend:
  name: backend
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  image:
    repository: ghcr.io/alexdenisova/pantry-tracker-backend
    pullPolicy: IfNotPresent
    tag: ""
  livenessPath: &livenessPath /health
  readinessPath: *livenessPath
  command:
    - pantry-tracker
    - run
  port: 8080
  ingressPath: /api(/|$)(.*)
  configMapValues:
    APP__SOCKET: 0.0.0.0:8080
    APP__DEBUG: "false"
  secretValues:
    APP__DATABASE_URL: ""
    APP__REDIS_URL: ""

pantryTrackerFrontend:
  name: frontend
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m
  image:
    repository: ghcr.io/alexdenisova/pantry-tracker-frontend
    pullPolicy: IfNotPresent
    tag: ""
  port: 5137
  ingressPath: /

ingress:
  enabled: true
  host: "pantry-tracker.alexdenisova.ru"
  className: "ingress-nginx"
  tls:
    secretName: pantry-tracker-tls
    key: ""
    certificate: ""

postgresMigrations:
  name: postgres-migrations
  command:
    - pantry-tracker
    - migrate
