{{- with .Values.kettleWeigher -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kettle-weigher.name" $ }}
  labels:
    {{- include "kettle-weigher.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  {{- toYaml .configMapValues | nindent 2 }}
{{- end -}}
