{{- if .Values.ingress.enabled }}
{{- with .Values.kettleWeigher -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kettle-weigher.name" $ }}
  labels:
    {{- include "kettle-weigher.labels" $ | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      secretName: {{ include "kettle-weigher.tls_secret" $ }}
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ .ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kettle-weigher.name" $ }}
                port:
                  number: {{ get (include "kettle-weigher.servicePort" $ | fromYaml) "port" }}
{{- end }}
{{- end }}
