{{- with .Values.kettleWeigher -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kettle-weigher.name" $ }}
  labels:
    {{- include "kettle-weigher.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports: 
    {{- include "kettle-weigher.servicePort" $ | fromYaml | list | toYaml | nindent 4 }}
  selector:
    {{- include "kettle-weigher.selectorLabels" $ | nindent 4 }}
{{- end -}}
