name: Helm Chart Deploy
description: Pipeline for helm chart deployment.

inputs:
  helm_chart:
    description: Helm chart path
    required: true
  values_path:
    description: Path to directory with values
    required: true
  release_name:
    description: Release name
    required: false
    default: app
  namespace:
    description: Release namespace
    required: true
  gpg_key_b64:
    description: Base64 encoded private key
    required: true
  values_pattern:
    description: Wildcard for values files
    required: false
    default: "*values.yaml"
  secrets_pattern:
    description: Wildcard for secrets files
    required: false
    default: "*sops.yaml"

runs:
  using: composite
  steps:
    - name: Upgrade Helm Chart
      shell: bash
      run: |-
        values_dir=$(realpath ${{ inputs.values_path }})
        common_dir=$(dirname ${values_dir})
        HLM_VALUES=($(find "${common_dir}" "${values_dir}" -maxdepth 1 -type f -iname "${{ inputs.values_pattern }}"))
        HLM_SECRETS=($(find "${common_dir}" "${values_dir}" -maxdepth 1 -type f -iname "${{ inputs.secrets_pattern }}"))
        command="helm upgrade --install --wait --wait-for-jobs --timeout 20m --namespace ${{ inputs.namespace }} --create-namespace"
        for value in "${HLM_VALUES[@]}"; do
          command="$(printf '%s --values %s' "$command" "$value")"
        done
        for value in "${HLM_SECRETS[@]}"; do
          command="$(printf '%s --values secrets://%s' "$command" "$value")"
        done
        for i in $(find "${values_dir}" -maxdepth 1 -type f -iname '*.env' | sort); do
          eval $(sed -e 's/^/export /' "${i}")
        done
        command="$(printf '%s %s %s' "$command" "${{ inputs.release_name }}" "${{ inputs.helm_chart }}")"
        echo "$command"
        eval "$command"
