---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "speech-to-text.name" . }}
  labels:
    {{- include "speech-to-text.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: main
      namespace: envoy-gateway-system
  hostnames: {{ .Values.gatewayAPI.hostnames }}
  rules:
    - matches:
        - path:
            value: /
            type: PathPrefix
      backendRefs:
        - kind: Service
          name: {{ include "speech-to-text.name" . }}
          port: {{ get (include "speech-to-text.servicePort" . | fromYaml) "port" }}
          weight: 1
