---
registry_secret:
  name: registrypullsecret
  data: ""

configMapValues: {}
secretValues: {}

image:
  repository: ghcr.io/alexdenisova/google-calendar-utility
  pullPolicy: IfNotPresent
  tag: ""

calendarSync:
  enable: true
  name: calendar-sync
  schedule: "0 0 * * *"
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  command:
    - google-calendar-utility
    - sync
  googlePrivateKey: ""

signUp:
  enable: true
  name: class-signup
  schedule: "0 0 * * *"
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  command:
    - google-calendar-utility
    - sign-up
  config:
    timezone: Europe/Moscow
    offsetWeeks: 1
    holiYoga: []
    plastilin: []
