---
registry_secret:
  name: registrypullsecret
  data: ""

googleCalendarUtility:
  name: google-calendar-utility
  schedule: "0 0 * * *"
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  image:
    repository: ghcr.io/alexdenisova/google-calendar-utility
    pullPolicy: IfNotPresent
    tag: ""
  command:
    - google-calendar-utility
  configMapValues:
    GCU__GOOGLE_PRIVATE_KEY: /google.key
  secretValues:
    GCU__GOOGLE_EMAIL: ""
    GCU__GOOGLE_KEY_ID: ""
    GCU__GOOGLE_CALENDAR_ID: ""
    GCU__HOLI_USERNAME: ""
    GCU__HOLI_PASSWORD: ""
  googlePrivateKey: ""
