calendarSync:
  schedule: "0 * * * *"
signUp:
  schedule: "0 9 * * *"
  config:
    timezone: Europe/Moscow
    offsetWeeks: 1
    classes:
      holiYoga:
        - name: Хатха йога (All Level)
          weekday: Tue
          startTime: 20:00
        - name: Хатха йога (All Level)
          weekday: Thu
          startTime: 20:00
        - name: "Виньяса йога (All Level)"
          weekday: Sat
          startTime: 12:00
