---
registry_secret:
  name: registrypullsecret
  data: ""

certificate:
  host: &host kettle-weigher.alexdenisova.ru
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

ingress:
  enabled: true
  host: *host
  className: "ingress-nginx"

kettleWeigher:
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  image:
    repository: ghcr.io/alexdenisova/kettle-weigher
    pullPolicy: IfNotPresent
    tag: ""
  livenessPath: &livenessPath /health
  readinessPath: *livenessPath
  command:
    - kettle-weigher
  port: 8080
  ingressPath: /
  configMapValues: {}
  secretValues: {}
