---
registry_secret:
  name: registrypullsecret
  data: ""

ingress:
  enabled: true
  host: "kettle-weigher.alexdenisova.ru"
  className: "ingress-nginx"
  # tls:
  #   secretName: kettle-weigher-tls
  #   key: ""
  #   certificate: ""

kettleWeigher:
  name: kettle-weigher
  replicaCount: 1
  annotations: {}
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
  image:
    repository: ghcr.io/alexdenisova/kettle-weigher
    pullPolicy: IfNotPresent
    tag: ""
  livenessPath: &livenessPath /health
  readinessPath: *livenessPath
  command:
    - kettle-weigher
  port: 8080
  ingressPath: /
  configMapValues: {}
  secretValues: {}
