{{- with .Values.googleCalendarUtility -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "google-calendar-utility.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  GCU__GOOGLE_PRIVATE_KEY: "{{ .googlePrivateKey.directory }}/private.key"
  {{- if .configMapValues -}}
  {{- toYaml .configMapValues | nindent 2 }}
  {{- end -}}
{{- end -}}
