---
apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "google-calendar-utility.privateKeyName" $ }}"
  labels:
    {{- include "google-calendar-utility.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  private.key: {{ .Values.googleCalendarUtility.googlePrivateKey | b64enc }}
