---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "google-calendar-utility.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  {{- range $k, $v := .Values.secretValues }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
