{{- if .Values.signUp.enable -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "google-calendar-utility.signupConfigMap" $ }}"
  labels:
    {{- include "google-calendar-utility.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  {{ base (include "google-calendar-utility.signupConfigPath" $) }}: |-
    {{- toYaml .Values.signUp.config | nindent 4 }}
{{- end -}}
