name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine changed files 
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            all:
              - 'helm-charts/**'
              - 'values/**'
            pantry-tracker:
              - 'helm-charts/pantry-tracker/**'
              - 'values/pantry-tracker/**'
              - 'values/*'
            google-calendar-utility:
              - 'helm-charts/google-calendar-utility/**'
              - 'values/google-calendar-utility/**'
              - 'values/*'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        if: steps.filter.outputs.all == 'true'
        with:
          gpg_private_key: ${{ secrets.HLM_GPG_PRIVATE_KEY }}
      - name: Pre Deploy
        uses: ./.github/actions/pre-deploy
        if: steps.filter.outputs.all == 'true'
        with:
          kubeconfig_b64: ${{ secrets.HLM_KUBECONFIG_B64 }}
      - name: Deploy Pantry Tracker
        uses: ./.github/actions/deploy
        if: steps.filter.outputs.pantry-tracker == 'true'
        with:
          helm_chart: "helm-charts/pantry-tracker"
          values_path: "values/pantry-tracker"
          release_name: "pantry-tracker"
          namespace: "pantry-tracker"
      - name: Deploy Google Calendar Utility
        uses: ./.github/actions/deploy
        if: steps.filter.outputs.google-calendar-utility == 'true'
        with:
          helm_chart: "helm-charts/google-calendar-utility"
          values_path: "values/google-calendar-utility"
          release_name: "google-calendar-utility"
          namespace: "calendar-utility"
