name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pantry-tracker:
              - 'helm-charts/pantry-tracker/**'
              - 'values/pantry-tracker/**'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: List keys
        run: gpg -K
      - name: sops check
        run: |-
          curl -sLo sops https://github.com/mozilla/sops/releases/download/v3.7.2/sops-v3.7.2.linux.amd64
          sudo mv ./sops /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

          sops -e test.yaml
          sops -d test.sops.yaml
      - name: Deploy Pantry Tracker
        uses: ./.github/actions/deploy
        with:
          helm_chart: "helm-charts/pantry-tracker"
          values_path: "values/pantry-tracker"
          release_name: "pantry-tracker"
          namespace: "pantry-tracker"
          kubeconfig_b64: ${{ secrets.HLM_KUBECONFIG_B64 }}
          gpg_key_b64: ${{ secrets.HLM_GPG_KEY_B64 }}
          gpg_key: ${{ secrets.GPG_PRIVATE_KEY }}
