name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pantry-tracker:
              - 'helm-charts/pantry-tracker/**'
              - 'values/pantry-tracker/**'
      - name: Deploy Pantry Tracker
        uses: ./.github/actions/deploy
        with:
          helm_chart: "helm-charts/pantry-tracker"
          values_path: "values/pantry-tracker"
          release_name: "pantry-tracker"
          namespace: "pantry-tracker"
          kubeconfig_b64: $HLM_KUBECONFIG_B64
          gpg_key_b64: $TESTING_SECRETS

